version: '3.8'
services:
  dcc-kali:
    container_name:  innovanon/dcc-kali
    ports:
      - "0.0.0.0:3632:3632"
      - "0.0.0.0:3633:3633"
    volumes:
      - dcc-kali:/var/cache/ccache:rw
      - ccache-redis:/etc/ccache.conf.d/:ro
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
    #  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
      test: ["CMD-SHELL", "distcc --show-hosts && ccache -s"]
      interval:      1m
      timeout:       3s
      retries:       10
    depends_on:
      redis:
         condition: service_started
      syslog:
         condition: service_started
      #  condition:   service_healthy

volumes:
  dcc-kali:

