version: '3.8'
services:
  dcc-voidlinux:
    image: innovanon/dcc-voidlinux
    container_name:  dcc-voidlinux
    ports:
      - "0.0.0.0:3638:3632"
      - "0.0.0.0:3639:3633"
    volumes:
      - dcc-voidlinux:/var/cache/ccache:rw
      - ccache-etc:/etc/ccache.conf.d/:ro
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
    #  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
      test: ["CMD-SHELL", "distcc --show-hosts && ccache -s"]
      interval:      1m
      timeout:       3s
      retries:       10
    depends_on:
      redis:
         condition: service_started
      syslog:
         condition: service_started
      #  condition:   service_healthy

volumes:
  dcc-voidlinux:

