version: '3.8'
services:
  syslog:
    image:           innovanon/pgrsyslog
    container_name:  syslog
    ports:
      - "0.0.0.0:514:514/udp"
      - "0.0.0.0:6514:6514"
    volumes:
      - syslog-etc:/etc/rsyslog.d:ro
      - syslog-log:/var/log
    restart:         always
    depends_on:
      db:
        condition:   service_healthy

volumes:
  syslog-etc:
  syslog-log:

