version: '3.8'
services:
  dcc-ubuntu:
    image: innovanon/dcc-ubuntu
    container_name:  dcc-ubuntu
    ports:
      - "0.0.0.0:3636:3632"
      - "0.0.0.0:3637:3633"
    volumes:
      - dcc-ubuntu:/var/cache/ccache:rw
      - ccache-redis:/etc/ccache.conf.d/:ro
      - syslog-client:/etc/rsyslog.d:ro
    restart:         always
    #network_mode:    service:vpn-s1
    healthcheck:
    #  test: ["CMD-SHELL", "exec 3<> /dev/tcp/0.0.0.0/3633 ; cat <&3 ; exec 3<&-"]
      test: ["CMD-SHELL", "distcc --show-hosts && ccache -s"]
      interval:     10s
      timeout:       3s
      retries:       10
    depends_on:
      redis:
        condition:   service_started
      syslog:
        condition:   service_started

volumes:
  dcc-ubuntu:

