name: Dockerized DistCC with Server-Side CCache (VoidLinux)
permissions:
  contents: write

on:
  schedule:
    - cron: '* * 1 * *'
  #[workflow_call]
  push:
    branches: [ "voidlinux" ]
  pull_request:
    branches: [ "voidlinux" ]
  workflow_dispatch:

jobs:
  build:
    name: build package
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        path: "repo"

    # TODO new image
    - name: Authenticate with Docker Hub
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD
      env:
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Bump version and push tag
      id:   tag_version
      uses: mathieudutour/github-tag-action@v6.1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker Image
      working-directory: "repo"
      run: |
        docker build -t "innovanon/dcc-voidlinux:$TEAMHACK_VERSION" .
      env:
        TEAMHACK_VERSION: ${{ steps.tag_version.outputs.new_tag }}

    - name: Tag Docker Image
      run: |
        docker tag      "innovanon/dcc-voidlinux:$TEAMHACK_VERSION" \
                         innovanon/dcc-voidlinux:latest
      env:
        TEAMHACK_VERSION: ${{ steps.tag_version.outputs.new_tag }}

    - name: Deploy Docker Image
      run: |
        docker push      innovanon/dcc-voidlinux

